# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
# title:            Andrei Zhirnov
# tagline:          'A Jekyll theme'
description:      Andrei Zhirnov's personal webpage
url:              andreizhirnov.github.io
baseurl:          "/"


paginate:         5

# Custom vars
# version:          1.0

github:
  repo:           https://github.com/andreizhirnov/andreizhirnov.github.io

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag