# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
# title:            Andrei Zhirnov
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              andreizhirnov.github.io
baseurl:          /


paginate:         5

# Custom vars
# version:          1.0

github:
  repo:           https://github.com/andreizhirnov/andreizhirnov.github.io

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag